apiVersion: v1

kind: Pod

metadata:
  name: apiadapter
  labels:
    app: apiadapter

spec:
  containers:
    - name: apiadapter-container
      image: mabdockerid/apiadapter:latest
      env:
      # cluster ip on the Qourum Node 2
        - name: RPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: apiadapter-configmap
              key: RPC_ADDRESS
        - name: ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: apiadapter-configmap
              key: ACCOUNT
      # smart contract endpoint. will use /contractAddress and /abi to update the configuration of the API Adapter.
      # It will override the env. CONTRACT_ADDRESS value if set.
        - name : SMARTCONTRACT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: apiadapter-configmap
              key: SMARTCONTRACT_ENDPOINT
      ports:
        - containerPort: 3000
      imagePullPolicy: Always


---


apiVersion: v1
kind: Service
metadata:
  name: apiadapter-service
  labels:
    name: apiadapter-service

spec:
  selector:
    app: apiadapter

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer


